List<dynamic>categories=[
  {
    "_id":"",
    "title":"",
    "value":"",
    "imageUrl":"",
    "createdAt":"",
    "updatedAt":""
  },
   {
    "_id":"",
    "title":"",
    "value":"",
    "imageUrl":"",
    "createdAt":"",
    "updatedAt":""
  },
   {
    "_id":"",
    "title":"",
    "value":"",
    "imageUrl":"",
    "createdAt":"",
    "updatedAt":""
  },
   {
    "_id":"",
    "title":"",
    "value":"",
    "imageUrl":"",
    "createdAt":"",
    "updatedAt":""
  },
   {
    "_id":"",
    "title":"",
    "value":"",
    "imageUrl":"",
    "createdAt":"",
    "updatedAt":""
  },
   {
    "_id":"",
    "title":"",
    "value":"",
    "imageUrl":"",
    "createdAt":"",
    "updatedAt":""
  }
];
const restaurants=[
  {
    "_id":"",
    "title":"",
    "time":"",
    "imageUrl":"",
    "owner":"",
    "code":"",
    "logoUrl":"",
    "rating":"",
    "ratingCount":"",
    "coords":{
      "id":"2023",
      "latitude":"",
      "longitude":"",
      "address":"",
      "title":"",
      "latitudeDelta":"",
      "longtudeDelta":""
    }
  }
,
  {
    "_id":"",
    "title":"",
    "time":"",
    "imageUrl":"",
    "owner":"",
    "code":"",
    "logoUrl":"",
    "rating":"",
    "ratingCount":"",
    "coords":{
      "id":"2023",
      "latitude":"",
      "longitude":"",
      "address":"",
      "title":"",
      "latitudeDelta":"",
      "longtudeDelta":""
    }
  }
,
  {
    "_id":"",
    "title":"",
    "time":"",
    "imageUrl":"",
    "owner":"",
    "code":"",
    "logoUrl":"",
    "rating":"",
    "ratingCount":"",
    "coords":{
      "id":"2023",
      "latitude":"",
      "longitude":"",
      "address":"",
      "title":"",
      "latitudeDelta":"",
      "longtudeDelta":""
    }
  }
,
  {
    "_id":"",
    "title":"",
    "time":"",
    "imageUrl":"",
    "owner":"",
    "code":"",
    "logoUrl":"",
    "rating":"",
    "ratingCount":"",
    "coords":{
      "id":"2023",
      "latitude":"",
      "longitude":"",
      "address":"",
      "title":"",
      "latitudeDelta":"",
      "longtudeDelta":""
    }
  }
,
  {
    "_id":"",
    "title":"",
    "time":"",
    "imageUrl":"",
    "owner":"",
    "code":"",
    "logoUrl":"",
    "rating":"",
    "ratingCount":"",
    "coords":{
      "id":"2023",
      "latitude":"",
      "longitude":"",
      "address":"",
      "title":"",
      "latitudeDelta":"",
      "longtudeDelta":""
    }
  }
,
  {
    "_id":"",
    "title":"",
    "time":"",
    "imageUrl":"",
    "owner":"",
    "code":"",
    "logoUrl":"",
    "rating":"",
    "ratingCount":"",
    "coords":{
      "id":"2023",
      "latitude":"",
      "longitude":"",
      "address":"",
      "title":"",
      "latitudeDelta":"",
      "longtudeDelta":""
    }
  }
,
  {
    "_id":"",
    "title":"",
    "time":"",
    "imageUrl":"",
    "owner":"",
    "code":"",
    "logoUrl":"",
    "rating":"",
    "ratingCount":"",
    "coords":{
      "id":"2023",
      "latitude":"",
      "longitude":"",
      "address":"",
      "title":"",
      "latitudeDelta":"",
      "longtudeDelta":""
    }
  }

];
List<Map<String,dynamic>>foods=[
  {
    "_id":"",
    "title":"",
    "foodTags":"",
    "foodType":"",
    "code":"",
    "isAvailable":true,
    "restaurant":"",
    "rating":5,
    "ratingCount":"420",
    "description":"",
    "price":99,
    "additives":[
      {
        "_id":"","title":"","price":""
      },
       {
        "_id":"","title":"","price":""
      },
       {
        "_id":"","title":"","price":""
      },
       {
        "_id":"","title":"","price":""
      }
    ]
  }
];
const cart=[
  {
    "_id":"",
    "userId":"",
    "productId":{
      "_id":"",
      "title":"",
      "restaurant":"",
      "rating":5,
      "ratingCount":"150",
      "imageUrl":[
        "",""
      ]
    },
    "additives":["",""],
    "instructions":""
  }

,
  {
    "_id":"",
    "userId":"",
    "productId":{
      "_id":"",
      "title":"",
      "restaurant":"",
      "rating":5,
      "ratingCount":"150",
      "imageUrl":[
        "",""
      ]
    },
    "additives":["",""],
    "instructions":""
  }

,
  {
    "_id":"",
    "userId":"",
    "productId":{
      "_id":"",
      "title":"",
      "restaurant":"",
      "rating":5,
      "ratingCount":"150",
      "imageUrl":[
        "",""
      ]
    },
    "additives":["",""],
    "instructions":""
  }


];
const profile={
  "_id":"",
  "username":"",
  "email":"",
  "uid":"",
  "address":[],
  "userType":"",
  "profile":"",
  "updatedAt":""

};