// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBZ2xbevgKaKkh4ApJleDY6XJSkFD7EumY',
    appId: '1:933250682911:web:10282ae1af2c656615052a',
    messagingSenderId: '933250682911',
    projectId: 'restaurant-4d81e',
    authDomain: 'restaurant-4d81e.firebaseapp.com',
    storageBucket: 'restaurant-4d81e.appspot.com',
    measurementId: 'G-BF7PYREYZQ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCI1Gpp66HNLh-lr0W4evuBBOmWUtXsAtA',
    appId: '1:933250682911:android:7e3fe2808f0d8e0515052a',
    messagingSenderId: '933250682911',
    projectId: 'restaurant-4d81e',
    storageBucket: 'restaurant-4d81e.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCPvpQfqv5E2nSdaS8n_EyJ8kV9cbdItb4',
    appId: '1:933250682911:ios:3fc924c95b48dada15052a',
    messagingSenderId: '933250682911',
    projectId: 'restaurant-4d81e',
    storageBucket: 'restaurant-4d81e.appspot.com',
    iosClientId: '933250682911-73c35ehma9jdklivof02e2baeld53pqa.apps.googleusercontent.com',
    iosBundleId: 'com.example.multivendorApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCPvpQfqv5E2nSdaS8n_EyJ8kV9cbdItb4',
    appId: '1:933250682911:ios:3fc924c95b48dada15052a',
    messagingSenderId: '933250682911',
    projectId: 'restaurant-4d81e',
    storageBucket: 'restaurant-4d81e.appspot.com',
    iosClientId: '933250682911-73c35ehma9jdklivof02e2baeld53pqa.apps.googleusercontent.com',
    iosBundleId: 'com.example.multivendorApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBZ2xbevgKaKkh4ApJleDY6XJSkFD7EumY',
    appId: '1:933250682911:web:805dbf645f751d0015052a',
    messagingSenderId: '933250682911',
    projectId: 'restaurant-4d81e',
    authDomain: 'restaurant-4d81e.firebaseapp.com',
    storageBucket: 'restaurant-4d81e.appspot.com',
    measurementId: 'G-KHWDY04YQ1',
  );
}
